#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
#kind es el tipo de archivo secret, con esto el cluster sabe que va codificado en base 64
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: postgres
    #meant that we can use arbitrary key pair values
type: Opaque
#el nombre de bd, usuario por defecto y la contraseña por defecto de postgres
data:
  # el correo es admin@admin.com
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  # la contraseña es academyjava
  PGADMIN_DEFAULT_PASSWORD: YWNhZGVteWphdmE=
  # el puerto es 80
  PGADMIN_PORT: ODA=