# Objeto que almacena variables de entorno que podrían contener datos sensibles como una contraseña
apiVersion: v1
# "kind" es el tipo de archivo Secret, con esto el cluster sabe que va codificado en base 64
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
# "type: Opaque" significa que podemos usar pares de clave-valor arbitrarios
type: Opaque
# Nombre de la base de datos, usuario por defecto y la contraseña
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWNhZGVteWphdmE=